export enum EServiceResponse {
    CARICO_OK = "CARICO_OK",
    UPDATE_OK = "UPDATE_OK",
    OK = "OK",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATE_FAILED = "UPDATE_FAILED",
    DELETE_FAILED = "DELETE_FAILED",
    DATA_INTEGRITY_ERROR = "DATA_INTEGRITY_ERROR",
    EMPTY_DTO = "EMPTY_DTO",
    EMPTY_ID = "EMPTY_ID",
    READ_FAILED = "READ_FAILED",
    CARICO_FAILED = "CARICO_FAILED",
    CARICO_GIA_EFFETTUATO = "CARICO_GIA_EFFETTUATO",
    ERRORE_SERVER_REMOTO = "ERRORE_SERVER_REMOTO",
    CREDENZIALI_VUOTE = "CREDENZIALI_VUOTE",
    CREDENZIALI_ERRATE = "CREDENZIALI_ERRATE",
    ARTICOLO_GIA_PRESENTE = "ARTICOLO_GIA_PRESENTE"
}